name: Module Version Bump 2

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  check-and-bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for changes in module
        id: check_changes
        run: |
          echo "Checking for changes in commoncore/ in the last 2 hours..."
          if git diff --quiet '@{5 hour ago}' HEAD -- commoncore/; then
            echo "No changes detected"
            echo "changed=0" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changed=1" >> $GITHUB_OUTPUT
          fi
          echo "Git diff exit code: $?"
          echo "Contents of GITHUB_OUTPUT:"
          cat $GITHUB_OUTPUT

      - name: Set up JDK 17
        if: steps.check_changes.outputs.changed == '1'
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Bump version
        if: steps.check_changes.outputs.changed == '1'
        run: |
          echo "Updating BOM version..."
          chmod +x ./gradlew
          ./gradlew publishBomModules
          fi

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == '1'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump version for myfeature module"
          git push
          fi