name: Module Version Bump

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  check-and-bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for changes in module
        id: check_changes
        run: |
          if git diff --quiet '@{3 hour ago}' HEAD -- commoncore/; then
            echo "changed=0" >> $GITHUB_OUTPUT
          else
            echo "changed=1" >> $GITHUB_OUTPUT
          fi

      - name: Check output
        run: |
          echo "Updating BOM version... $steps.check_changes.outputs.changed"

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          overwrite-settings: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Bump version
        if: steps.check_changes.outputs.changed == '1'
        run: |
          echo "Updating BOM version..."
          ./gradlew publishBomModules
        continue-on-error: true

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == '1'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump version for myfeature module"
          git push
        continue-on-error: true