name: Module Version Bump

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  check-and-bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for changes in module
        id: check_changes
        run: |
          git diff --quiet '@{1 day ago}' HEAD -- commoncore/
          echo "changed=$?" >> $GITHUB_OUTPUT

      - name: Bump version
        if: steps.check_changes.outputs.changed == '1'
        run: |
          echo "Updating BOM version..."
          ./gradlew publishBomModules

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == '1'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump version for myfeature module"
          git push